# Basic
title: ä»–å±±ä¹‹çŸ³ï¼Œå¯ä»¥æ”»ç‰
subtitle: åº„ç”Ÿæ™“æ¢¦è¿·è´è¶ï¼Œå¥½æ¢¦ç”±æ¥æœ€æ˜“é†’
#<a href="/merger.html">å¦‚æœä½ è§‰å¾—æˆ‘çš„æ–‡å­—å¯¹ä½ æœ‰æ‰€å¸®åŠ©ï¼Œä¹Ÿå¯ä»¥è¯·æˆ‘å–æ¯å’–å•¡~</a>
welcome_message: <a target="_blank" href="https://www.aliyun.com/minisite/goods?source=5176.11533457&userCode=j6bryttg">é˜¿é‡Œäº‘æœåŠ¡å™¨ï¼Œé™æ—¶ç§’æ€ä»·ä½è‡³86/å¹´ï¼Œåˆ¸å66/å¹´</a><br/><a target="_blank"  href="https://ac.aliyun.com/application/webdesign/sumei?source=5176.11533457&userCode=j6bryttg">é˜¿é‡Œäº‘å»ºç«™ é€Ÿæˆç¾ç«™ - åƒå¥—æ¨¡æ¿ï¼Œä»·æ ¼ä½è‡³500å…ƒ</a>

description: <span>æˆ‘æ˜¯èƒ¡æ±‰ä¸‰<br/>è‹±æ–‡åhuhansome<br/>æ¬¢è¿å…‰ä¸´æˆ‘çš„è€çª<br/>æŠ€æœ¯æ˜¯å­¦ä¸å®Œçš„<br/>ä½†æ˜¯å¯ä»¥å°½é‡å¤šå­¦<br/>åŠ æ²¹ğŸ’ª</span>
creator: <a href="">@huhansome</a>
seodescription: <span>æˆ‘æ˜¯èƒ¡æ±‰ä¸‰,è‹±æ–‡åhuhansomeã€‚æ¬¢è¿å…‰ä¸´æˆ‘çš„è€çªï¼Œè¿™é‡Œæœ‰å®ç”¨æŠ€å·§åˆ†äº«ï¼Œä¹Ÿæœ‰æŠ€æœ¯ã€æ¸¸æˆç»éªŒäº¤æµï¼Œè¿˜æœ‰çŸ¥è¯†æ™®åŠã€ç§‘æŠ€è§£è¯»ï¼Œæ›´æœ‰ç½‘èµšç»éªŒåˆ†äº«ã€‚</span>

url: "https://huhansome.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: green

blog_button:
    title: åšå®¢
    description: è®¿é—®åšå®¢

nav:
    - {title: äº‘æœåŠ¡å™¨, description: é˜¿é‡Œäº‘æœåŠ¡å™¨ï¼Œé™æ—¶ç§’æ€ä»·ä½è‡³86/å¹´ï¼Œåˆ¸å66/å¹´, url: 'https://huhansome.github.io/2020/08/aliyunfuwu/'}
    - {title: äº‘å»ºç«™, description: é˜¿é‡Œäº‘å»ºç«™ é€Ÿæˆç¾ç«™ - åƒå¥—æ¨¡æ¿ï¼Œä»·æ ¼ä½è‡³500å…ƒ, url: 'https://ac.aliyun.com/application/webdesign/sumei?source=5176.11533457&userCode=j6bryttg'}
    - {title: æ‰“èµ, description: è¯·ä»–å–å’–å•¡, url: '/merger.html'}

# Pagination
plugins: [jekyll-paginate, jekyll-sitemap]
paginate: 6
paginate_path: "page/:num/"

# Comment
#comment:
#    disqus: onevcat
    # duoshuo:
# Social
social:
    youtube: UCb4enWjBmzSLE5iFn7xpXBQ
    github: huhansome
    twitter: huhansome
    mail: hucd_mail@yeah.net

# Google Analytics
#ga:
#    id: UA-169358395-1
#    host: onevcat.com
